# Generated by Django 6.0.5 on 2026-06-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost_contactmessage_customerinquiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
