# Generated by Django 6.0.5 on 2026-06-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_feedback_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('Team', 'Team'), ('Events', 'Events'), ('Projects', 'Projects'), ('Office', 'Office')], default='Team', max_length=50),
        ),
    ]
