# Generated by Django 6.0.5 on 2026-06-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_galleryimage_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryimage',
            old_name='uploaded_at',
            new_name='uploaded_date',
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
    ]
