# Generated by Django 6.0.5 on 2026-06-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_uploaded_at_galleryimage_uploaded_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author_role',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
